<?php

declare(strict_types=1);

return [
    ['POST', '/api/auth/register'],
    ['POST', '/api/auth/login'],
    ['POST', '/api/auth/logout'],
    ['GET', '/api/auth/me'],
    ['GET', '/api/wallet/summary'],
    ['GET', '/api/wallet/withdraw-progress'],
    ['GET', '/api/exchange-rate'],
    ['GET', '/api/wallet/checkin-status'],
    ['POST', '/api/wallet/checkin'],
    ['POST', '/api/wallet/claim-reward'],
    ['GET', '/api/wallet/achievements'],
    ['GET', '/api/wallet/activity'],
    ['POST', '/api/wallet/withdraw'],
    ['GET', '/api/wallet/topup-config'],
    ['POST', '/api/wallet/topup/submit-receipt'],
    ['GET', '/api/referrals/info'],
    ['POST', '/api/invest/lock'],
    ['GET', '/api/invest/locks'],
    ['GET', '/api/tasks'],
    ['POST', '/api/tasks/:id/verify'],
    ['POST', '/api/spin/play'],
    ['POST', '/api/notifications/subscribe'],
    ['POST', '/api/notifications/unsubscribe'],
    ['GET', '/api/notifications'],
    ['POST', '/api/notifications/read'],
    ['POST', '/api/admin/login'],
    ['POST', '/api/admin/logout'],
    ['GET', '/api/admin/me'],
    ['GET', '/api/admin/overview'],
    ['GET', '/api/admin/users'],
    ['GET', '/api/admin/users/:id'],
    ['POST', '/api/admin/users/:id/suspend'],
    ['POST', '/api/admin/users/:id/reactivate'],
    ['POST', '/api/admin/users/:id/adjust-balance'],
    ['GET', '/api/admin/withdrawals'],
    ['POST', '/api/admin/withdrawals/:id/approve'],
    ['POST', '/api/admin/withdrawals/:id/reject'],
    ['GET', '/api/admin/topups'],
    ['POST', '/api/admin/topups/:id/approve'],
    ['POST', '/api/admin/topups/:id/reject'],
    ['GET', '/api/admin/topups/:id/receipt'],
    ['GET', '/api/admin/tasks'],
    ['POST', '/api/admin/tasks'],
    ['PUT', '/api/admin/tasks/:id'],
    ['DELETE', '/api/admin/tasks/:id'],
    ['GET', '/api/admin/achievements'],
    ['POST', '/api/admin/achievements'],
];
