import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { adminApi } from '../../lib/api/admin'

export default function LoanRequestsPage() {
  const navigate = useNavigate()
  const [status, setStatus] = useState('pending')
  const [requests, setRequests] = useState([])
  const [selected, setSelected] = useState(null)
  const [reason, setReason] = useState('')
  const [preview, setPreview] = useState(null)
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)

  const load = () => adminApi.listLoanRequests(status).then((data) => setRequests(data.requests || [])).catch((err) => setError(err.message))
  useEffect(() => { load() }, [status])
  const approve = async (id) => { if (!window.confirm('Approve and disburse the principal amount?')) return; setBusy(true); try { await adminApi.approveLoanRequest(id); await load() } catch (err) { setError(err.message) } finally { setBusy(false) } }
  const reject = async () => { if (!selected || !reason.trim()) return setError('A rejection reason is required.'); setBusy(true); try { await adminApi.rejectLoanRequest(selected.id, reason); setSelected(null); setReason(''); await load() } catch (err) { setError(err.message) } finally { setBusy(false) } }
  const showDocument = async (id, type) => { try { setPreview(await adminApi.fetchLoanDocument(id, type)) } catch (err) { setError(err.message) } }
  return <AdminShell title="Loan Requests" onBack={() => navigate('/admin')} error={error}><div className="mb-6 flex gap-2">{['pending', 'approved', 'rejected'].map((item) => <button key={item} onClick={() => setStatus(item)} className={`rounded px-4 py-2 capitalize ${status === item ? 'bg-blue-600' : 'border border-gray-700 bg-gray-800 text-gray-400'}`}>{item}</button>)}</div><div className="overflow-hidden rounded-lg border border-gray-700 bg-gray-800"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-gray-700"><tr><th className="px-4 py-3 text-left">Applicant</th><th className="px-4 py-3 text-left">Request</th><th className="px-4 py-3 text-left">Profile</th><th className="px-4 py-3 text-left">Documents</th><th className="px-4 py-3 text-center">Actions</th></tr></thead><tbody>{requests.map((item) => <tr key={item.id} className="border-t border-gray-700 align-top"><td className="px-4 py-3"><p className="font-medium">{item.full_name}</p><p className="text-xs text-gray-400">{item.email}</p></td><td className="px-4 py-3"><p>Principal: ₦{(item.amount_kobo / 100).toLocaleString()}</p><p className="text-gray-400">Fee: ₦{(item.fee_kobo / 100).toLocaleString()}</p><p className="text-green-300">Repay: ₦{(item.total_repayable_kobo / 100).toLocaleString()}</p><p className="mt-2 max-w-xs text-xs text-gray-400">{item.purpose}</p></td><td className="px-4 py-3"><p>{item.employment_status}</p><p className="text-xs text-gray-400">{item.monthly_income_range}</p></td><td className="px-4 py-3"><div className="flex flex-col gap-2"><button onClick={() => showDocument(item.id, 'id')} className="text-left text-blue-300 underline">View ID</button><button onClick={() => showDocument(item.id, 'address')} className="text-left text-blue-300 underline">View address</button></div></td><td className="px-4 py-3 text-center">{item.status === 'pending' ? <div className="flex justify-center gap-2"><button disabled={busy} onClick={() => approve(item.id)} className="rounded bg-green-600 px-3 py-1 text-xs">Approve</button><button disabled={busy} onClick={() => setSelected(item)} className="rounded bg-red-600 px-3 py-1 text-xs">Reject</button></div> : <span className="capitalize text-gray-400">{item.status}</span>}</td></tr>)}</tbody></table></div>{requests.length === 0 ? <p className="p-8 text-center text-gray-400">No loan requests found</p> : null}</div>{selected ? <RejectModal title="Reject loan request" reason={reason} setReason={setReason} close={() => { setSelected(null); setReason('') }} submit={reject} busy={busy} /> : null}<Preview preview={preview} close={() => { URL.revokeObjectURL(preview.url); setPreview(null) }} /></AdminShell>
}

function AdminShell({ title, onBack, error, children }) { return <div className="min-h-screen bg-gray-900 text-white"><header className="sticky top-0 z-20 border-b border-gray-700 bg-gray-800"><div className="mx-auto flex max-w-7xl items-center gap-4 px-4 py-4"><button onClick={onBack} className="text-gray-400 hover:text-white">← Back</button><h1 className="text-2xl font-bold">{title}</h1></div></header><main className="mx-auto max-w-7xl px-4 py-8">{error ? <p className="mb-4 rounded border border-red-700 bg-red-900 p-3 text-red-200">{error}</p> : null}{children}</main></div> }
function RejectModal({ title, reason, setReason, close, submit, busy }) { return <div className="fixed inset-0 z-30 flex items-center justify-center bg-black/75 p-4"><div className="w-full max-w-md rounded-lg bg-gray-800 p-6"><h2 className="text-lg font-semibold">{title}</h2><textarea value={reason} onChange={(event) => setReason(event.target.value)} rows="4" placeholder="Reason for rejection" className="mt-4 w-full rounded border border-gray-600 bg-gray-700 p-3 text-white" /><div className="mt-4 flex gap-3"><button onClick={close} className="flex-1 rounded bg-gray-700 px-4 py-2">Cancel</button><button disabled={busy} onClick={submit} className="flex-1 rounded bg-red-600 px-4 py-2">Reject</button></div></div></div> }
function Preview({ preview, close }) { if (!preview) return null; return <div className="fixed inset-0 z-30 flex items-center justify-center bg-black/80 p-4" onClick={close}><div className="max-h-[90vh] max-w-4xl rounded-lg bg-white p-2" onClick={(event) => event.stopPropagation()}>{preview.type === 'application/pdf' ? <iframe src={preview.url} title="Loan document" className="h-[82vh] w-[min(80vw,60rem)]" /> : <img src={preview.url} alt="Loan document" className="max-h-[82vh] max-w-full object-contain" />}<button onClick={close} className="mt-2 w-full rounded bg-gray-800 px-4 py-2 text-white">Close</button></div></div> }
